<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Code Generation</h3>
            </div>
            <div class="panel-body">
                
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="panel panel-default"> 
            <div class="panel-heading">
                <h3 class="panel-title">Sku list</h3>
            </div>            
            <ul class="list-group">
                <?php foreach($this->skuList as $sku){ ?>
                    <li class="list-group-item list-group-item-<?php if($sku->completed){ echo "success";}else{echo "info";} ?>"><?php echo $sku->name; ?><span class="badge"><a href="/system/codes/generate/<?php echo $sku->id; ?>">Create codes</a></span></li>
                <?php } ?>
             </ul>
            <div class="panel-body">
                <p><a class="btn btn-success pull-right" href="/system/codes/create-all">Generate All &raquo;</a></p>
            </div>
        </div>
    </div>
    
</div>
<?php 
if(is_array($this->messages)){ 
    $messageBody = '';
    foreach($this->messages as $message){
        $messageBody .= '<p>'.$message.'</p>';
    }  
?>
<script>
    $('#myModalLabel').html('System Message');
    $('#myModal .modal-body').html('<?php echo $messageBody;?>');
    $('#myModal').modal('show');
</script>
<?php }?>

